### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [missena-corp/ir-gtm-widget#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.merchantKey and data.pageData.locale when generating the url
const url = apiUrl+data.merchantKey+'&locale='+data.pageData.locale;

**Comment by pdamoc** [comment]
The identified issue has been resolved. Thank you for the feedback.
